#!/usr/bin/env python3
"""Generate native/cmake/shipped_files.cmake from native/deps/shipped_files.toml.

Spec: Halcyon/docs/logs/2026-09-12/platform-parity-plan.md, WI-15 step 15.2.1.
CMake cannot read TOML, so the declaration's file names are transcribed once
into a generated, checked-in CMake include defining, per platform:
    CEYX_SHIPPED_<PLATFORM>_DECODER
    CEYX_SHIPPED_<PLATFORM>_COMPANIONS
<PLATFORM> is the platform key upper-cased (WINDOWS, LINUX, MACOS, ANDROID).

`--check` regenerates in memory and diffs against the committed file,
exiting non-zero and naming the difference if they disagree -- this is what
native/scripts/tests/test_gen_shipped_files_cmake.py's staleness test calls,
so the generated artefact cannot silently drift from its TOML source (the
same "derive from the declaring side" correction the stage-1 AOT product
list already got).

Usage:
    gen_shipped_files_cmake.py              # regenerate and overwrite
    gen_shipped_files_cmake.py --check       # verify up to date, no write
"""
import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import read_shipped_files as rsf  # noqa: E402

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_PATH = REPO_ROOT / "native" / "cmake" / "shipped_files.cmake"

_HEADER = """# shipped_files.cmake -- GENERATED FILE, do not hand-edit.
#
# Generated by native/scripts/gen_shipped_files_cmake.py from
# native/deps/shipped_files.toml (WI-15 step 15.2.1). Regenerate with:
#   python3 native/scripts/gen_shipped_files_cmake.py
# native/scripts/tests/test_gen_shipped_files_cmake.py asserts this file is
# up to date with the TOML (regenerate-and-diff), so it cannot drift from
# its source.
"""


def render(platforms):
    lines = [_HEADER]
    for platform in sorted(platforms):
        entry = platforms[platform]
        upper = platform.upper()
        lines.append(f'set(CEYX_SHIPPED_{upper}_DECODER "{entry["decoder"]}")')
        companions = ";".join(entry["companions"])
        lines.append(f'set(CEYX_SHIPPED_{upper}_COMPANIONS "{companions}")')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--declaration", default=None, help="override path to shipped_files.toml")
    parser.add_argument("--output", default=None, help="override output path")
    parser.add_argument("--check", action="store_true", help="verify the committed file is up to date; do not write")
    args = parser.parse_args(argv)

    output_path = pathlib.Path(args.output) if args.output else DEFAULT_OUTPUT_PATH

    try:
        platforms = rsf.load_declaration(args.declaration)
    except (rsf.DeclarationError, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    rendered = render(platforms)

    if args.check:
        if not output_path.exists():
            print(f"error: {output_path} does not exist -- run without --check to generate it", file=sys.stderr)
            return 1
        current = output_path.read_text()
        if current != rendered:
            print(f"error: {output_path} is STALE relative to {args.declaration or 'native/deps/shipped_files.toml'}", file=sys.stderr)
            print("--- committed ---", file=sys.stderr)
            print(current, file=sys.stderr)
            print("--- regenerated ---", file=sys.stderr)
            print(rendered, file=sys.stderr)
            return 1
        print(f"OK: {output_path} is up to date")
        return 0

    output_path.write_text(rendered)
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
