"""Shell-prohibition allowlist. DATA + one derived count.

Owned in push 2 by WI-4 (this push's guard WI). Per D2/the ratchet ruling
(docs/logs/2026-09-13/pyci-plan.md "Push cadence and the guard ratchet"):
this starts at the FULL set of run-step bodies that are not yet a single
`python3 native/scripts/ci.py <command>` line, across EVERY workflow file
under `.github/workflows/*.yml` -- NOT just the four "leg" workflows plus
build.yml the work-package table names. Rule 1 (check_shell_prohibition.py)
scans every workflow file with no exceptions, so the six `*_dist_*.yml`
workflows (heif/jxl/webp x android/windows) are in MUST_STAY too, even
though no named WI currently owns migrating them.

Every migrated leg's push must DELETE its entries here and decrement
ALLOWLIST_SIZE_EXPECTED in the same commit; a loosening (an added entry, or
a raised pin with no corresponding deletion) is therefore always a visible
two-line diff.

Generated by running native/scripts/ci/workflow_scan.py against every
workflow file's CURRENT `run:` steps at push-2 tip and keeping every step
whose body is not exactly one line matching the required Python-invocation
pattern. Reasons:
  * 6 entries cite C-G14 (permanent must-stay: pre-checkout bootstrap,
    Python provisioning, apt package list, all-platforms-green, Windows LF
    line endings, the two deps-pytest-suite call sites under UR-1).
  * 5 entries cite C-G14 #8 / Q2 (the parked `publish` job).
  * 2 entries cite Q4 (the `verify-dart` job, outside this campaign's scope).
  * 76 entries carry a shared generic reason: not yet migrated to
    native/scripts/ci/, pending their leg's push per the work-package table.
  * 30 entries (the `*_dist_*.yml` workflows) carry a second generic reason
    noting they have no named migrating WI at all yet -- a gap surfaced
    during WI-4 implementation and reported to the leader, not silently
    absorbed into the first generic reason.

`GRANDFATHERED_SHELL_FILES` starts from Q6 (`fetch_symbol_absent_fixtures.sh`,
inside the very package this campaign declares Python-only) and, per the
SAME "grandfather what already exists rather than let a check invent new
scope creep" principle, is extended by three more pre-existing TRACKED shell
files discovered when Rule 2 was first run against this repo: none of the
three is CI-consumed by any of the workflow files the guard scans, none is
under `native/scripts/ci/`, and none is part of this campaign's migration
surface. Like Q6's own file, none is deleted (deletion needs a user ruling,
out of scope) or rewritten (also out of scope).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    workflow: str
    step_name: str
    reason: str


MUST_STAY: tuple = (
    Entry('android_build.yml', 'Install build prerequisites (apt)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Build dng_decoder_native for Android', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert HEIF was actually linked, not silently degraded (A-T8-FIX)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert JXL was explicitly disabled, not silently degraded (G1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert build capability vector via probe (S-E2)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Stage native artifacts', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Fail if the required Android .so set is incomplete (A-T8-FIX atomic group)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert required FFI exports present in Android .so (G6)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert fused-orientation kernel signals present in Android .so (Task 11 / G-E)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert decoder DT_NEEDED matches the resolved Android STL (A-T8-FIX libc++_shared handling)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Assert DT_NEEDED closure across the packaged Android .so set (Task 11 follow-up)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('android_build.yml', 'Measure and emit the minimum runtime floor (S-F1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'Flutter pub get', "verify-dart job (Q4): flutter/dart toolchain step, outside this campaign's CI Python-ization scope"),
    Entry('build.yml', 'dart analyze', "verify-dart job (Q4): flutter/dart toolchain step, outside this campaign's CI Python-ization scope"),
    Entry('build.yml', 'Derive vcpkg baseline from vcpkg.json', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'Install build prerequisites (Homebrew)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'Bootstrap vcpkg at the pinned baseline (D5)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'vcpkg install libwebp (arm64-osx-heif)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'Build test_decode target', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'Build test_device_handoff target', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('build.yml', 'Assert every platform leg reported success', 'C-G14 #5: all-platforms-green, reads needs.*.result only; must stay in YAML permanently'),
    Entry('build.yml', 'Assert no dist leg failed', 'C-G14 #8 / Q2 PARKED: publish job, tag-only, contents:write, unexercised by the CI loop; migration parked pending user ruling'),
    Entry('build.yml', 'List downloaded artifacts', 'C-G14 #8 / Q2 PARKED: publish job, tag-only, contents:write, unexercised by the CI loop; migration parked pending user ruling'),
    Entry('build.yml', 'Assert the required asset set (tag pushes only)', 'C-G14 #8 / Q2 PARKED: publish job, tag-only, contents:write, unexercised by the CI loop; migration parked pending user ruling'),
    Entry('build.yml', 'Package + lock (dry run, non-tag events)', 'C-G14 #8 / Q2 PARKED: publish job, tag-only, contents:write, unexercised by the CI loop; migration parked pending user ruling'),
    Entry('build.yml', 'Publish release assets + artifacts.lock (tag pushes only)', 'C-G14 #8 / Q2 PARKED: publish job, tag-only, contents:write, unexercised by the CI loop; migration parked pending user ruling'),
    Entry('heif_dist_android.yml', 'Install Ninja', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_android.yml', 'Install build prerequisites (apt)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_android.yml', 'Build the HEIF dist (Python carrier)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_android.yml', 'List the produced dist (complete)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Force LF line endings for all git operations', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Derive vcpkg baseline from vcpkg.json', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Install Ninja', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Locate clang-cl', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Bootstrap vcpkg at the pinned baseline (D1-a)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'vcpkg install de265 + aom (x64-windows-heif)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Assert the vcpkg aom artefact (static)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Export CEYX_VCPKG_PREFIX for the carrier', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'Build the HEIF dist (Python carrier)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('heif_dist_windows.yml', 'List the produced dist (complete)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_android.yml', 'Install Ninja', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_android.yml', 'Build the libjxl dist (Python carrier)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_android.yml', 'List the produced dist (complete)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_windows.yml', 'Force LF line endings for all git operations', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_windows.yml', 'Install Ninja', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_windows.yml', 'Locate clang-cl', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_windows.yml', 'Build the libjxl dist (Python carrier)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('jxl_dist_windows.yml', 'List the produced dist (complete)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('linux_build.yml', 'Install git + python3 into the container (pre-checkout, WI-14 step 14.5)', 'C-G14 #1: pre-checkout apt bootstrap -- no checkout yet, no interpreter; must stay in YAML permanently'),
    Entry('linux_build.yml', 'Derive vcpkg baseline from vcpkg.json', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Provision Python 3.11 inside the container (no hostedtoolcache)', 'C-G14 #2: Python 3.11 provisioning via $GITHUB_PATH; must stay in YAML permanently'),
    Entry('linux_build.yml', 'Verify the interpreter is alive and not from hostedtoolcache', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Install build prerequisites (apt)', "C-G14 #3: apt build prerequisite package list -- a legible package list is the step's entire value; must stay in YAML permanently"),
    Entry('linux_build.yml', 'Provide CMake >= 3.28 for Halide 21 (container has 3.22)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Bootstrap vcpkg at the pinned baseline (D5)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'vcpkg install libwebp + libde265 + aom (x64-linux-heif)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Assert the vcpkg libwebp artefact (static)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Build HEIF stack (libheif + libde265 + kvazaar + aom, Python carrier)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Build dng_decoder_native for Linux (Vulkan, single-stage host)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Verify Linux artifact (AC-L2/L3/L4/L5)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Assert no AVX-512 in the Linux .so (portable-baseline gate)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Assert fused-orientation kernel signals present in Linux .so (Task 11 / G-E)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Assert full codec capability vector via probe (G1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Assert build capability vector via probe (S-E2)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Compile + run functional capability probe (CI-T3)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Stage native artifacts', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Fail if no shared library was produced', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Assert the Linux shared-lib group is complete (atomic group)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('linux_build.yml', 'Verify DT_NEEDED references the staged HEIF companions', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Derive vcpkg baseline from vcpkg.json', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'D6 layer 1 — argv equivalence (renderer vs golden vs legacy shell)', "C-G14 #7 / UR-1 policy item: deps pytest suite call site (native/tests/run_dist_equivalence.py); stays pending WI-5's exemption"),
    Entry('macos_build.yml', 'Install build prerequisites (Homebrew)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Bootstrap vcpkg at the pinned baseline (D5)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'vcpkg install libwebp + libde265 + aom (${{ matrix.vcpkg_triplet }})', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Assert the vcpkg artefacts (libwebp static, libde265 shared)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Fetch vendored HEIF distribution (Python carrier)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', "Assert libde265's linkage in the produced dist (A5.2/A5.3)", "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Compile + run functional capability probe (D4/R-7)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Build dng_decoder_native via watchdog (native arm64)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Build host Halide generators + x86_64 AOT (cross stage 1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Cross-compile dng_decoder_native for x86_64 (cross stage 2)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Verify dylib was produced and has the expected architecture', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Build + run orientation capability probe (Task 11 / G-E)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Assert full codec capability vector via probe (G1, native leg)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Assert build capability vector via probe (S-E2, native leg)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Assert codec capability vector via configure log (G1, cross leg)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Assert build capability vector via probe (S-E2, cross leg)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Assert required FFI exports present in dylib (G3)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Stage native artifact', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('macos_build.yml', 'Measure and emit the minimum runtime floor (S-F1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('webp_dist_android.yml', 'Install Ninja', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_android.yml', 'Build the libwebp dist (Python carrier)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_android.yml', 'List the produced dist (complete)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_windows.yml', 'Force LF line endings for all git operations', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_windows.yml', 'Install Ninja', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_windows.yml', 'Locate clang-cl', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_windows.yml', 'Build the libwebp dist', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('webp_dist_windows.yml', 'List the produced dist (complete)', 'not yet migrated to native/scripts/ci/ (pyci python-ization campaign; the *_dist_* workflows are outside the named WI list but Rule 1 scans every workflow file, so they carry the same generic reason pending a future WI)'),
    Entry('windows_build.yml', 'Force LF line endings for all git operations', 'C-G14 #6: order-dependent relative to actions/checkout; must stay in YAML permanently'),
    Entry('windows_build.yml', 'Run deps unit suite (native Windows Python)', "C-G14 #7 / UR-1 policy item: deps pytest suite call site, pwsh deliberately (deps/run.py refuses an MSYS interpreter by design); stays pending WI-5's detected-then-exempted carve-out"),
    Entry('windows_build.yml', 'Install Ninja', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Locate clang-cl', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Locate the OpenMP runtime DLL', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Verify vulkan-1.lib is present', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Diagnose LibRaw patch failure (on failure only)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Build zlib 1.3.1 (static, /MT) for the Windows toolchain', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Configure (Ninja + clang-cl, Vulkan AOT target)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Assert JXL was statically linked, not silently degraded (G1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Diagnose configure failure (on failure only)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Build dng_decoder_native', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Diagnose build failure (on failure only)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Verify Windows artifact', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Assert fused-orientation kernel signals present in Windows DLL (Task 11 / G-E)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Assert full codec capability vector via probe (G1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Assert build capability vector via probe (S-E2)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Compile + run functional capability probe (CI-T3)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Stage native artifacts', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Measure and emit the minimum runtime floor (S-F1)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
    Entry('windows_build.yml', 'Assert the Windows shipped-file group is complete (atomic group)', "not yet migrated to native/scripts/ci/ (pyci python-ization campaign; see docs/logs/2026-09-13/pyci-plan.md work-package table for this leg's push)"),
)

# Q6 (the ci/ package's own pre-existing fixture fetcher) plus three more
# pre-existing tracked shell files discovered by WI-4's first real Rule-2
# run (see module docstring). Exact repo-relative path only -- no
# *additional* .sh/.bat/.ps1/.cmd file may join this list.
GRANDFATHERED_SHELL_FILES: tuple = (
    "native/scripts/ci/fetch_symbol_absent_fixtures.sh",
    "native/halide_runtime_fork/scripts/fetch_halide_v21_runtime.sh",
    "native/tests/data/make_h1_fixtures.sh",
    "plugin/tool/run_prod_shape_probe.sh",
)

ALLOWLIST_SIZE_EXPECTED: int = len(MUST_STAY)
