# shipped_files.cmake -- GENERATED FILE, do not hand-edit.
#
# Generated by native/scripts/gen_shipped_files_cmake.py from
# native/deps/shipped_files.toml (WI-15 step 15.2.1). Regenerate with:
#   python3 native/scripts/gen_shipped_files_cmake.py
# native/scripts/tests/test_gen_shipped_files_cmake.py asserts this file is
# up to date with the TOML (regenerate-and-diff), so it cannot drift from
# its source.

set(CEYX_SHIPPED_ANDROID_DECODER "libdng_decoder_native.so")
set(CEYX_SHIPPED_ANDROID_COMPANIONS "libheif.so;libde265.so")

set(CEYX_SHIPPED_LINUX_DECODER "libdng_decoder_native.so")
set(CEYX_SHIPPED_LINUX_COMPANIONS "libheif.so.1;libde265.so.0")

set(CEYX_SHIPPED_MACOS_DECODER "libdng_decoder_native.dylib")
set(CEYX_SHIPPED_MACOS_COMPANIONS "libjpeg.8.dylib;libheif.1.dylib;libde265.0.dylib;libomp.dylib")

set(CEYX_SHIPPED_WINDOWS_DECODER "dng_decoder_native.dll")
set(CEYX_SHIPPED_WINDOWS_COMPANIONS "heif.dll;libde265.dll;libomp140.x86_64.dll")
